### ISSUE TITLE
Version File Cruft Removal

### ISSUE THREAD

**Issue by Pshepp** [GLYCAM-Web/GMML#151]
The use of the `make-versions-file.bash` script within the `programs` dir is a bit silly. No need for the extra complexity

Steps to fix:
- [ ] figure out what is all dependent on the versions file, up n down the stack. Rip out those dependencies
- [ ] Go ahead and start letting cmake version our files in a more normal way (https://semver.org/), will need to wait for Olli to get back to finish helping wrap head around it
- [ ] Hopefully that's it, and we will begin checking the filenames for release data but we will need to make a programmatic way to increasing the versioning. I am lazy and don't wanna manually change everytime we gotta new release

**Comment by gitoliver** [comment]
Is this a gmml issue or higher up?

**Comment by Lachele** [comment]
This is how we build the info that goes into https://glycam.org/status/versions/

I wrote it so that each repo creates and maintains its own versioning info.  Each higher (gems, website) version of that script calls and collects output from lower versions.

The git hashes of the actual code being used are much more precise and reliable than any versioning scheme, so I do not want to let them go, even when we implement a more standard versioning.

**Comment by gitoliver** [comment]
Sounds like it should stay.
